In [58]:
import numpy as np

In [59]:
def update(V: np.ndarray):
    new_V = V.copy()
    for row in range(5):
        for col in range(5):
            v = 0
            for row_act, col_act in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                new_row = row + row_act
                new_col = col + col_act
                if row == 0 and col == 1:
                    v += 0.25 * (10 + 0.9 * V[4, 1])
                elif row == 0 and col == 3:
                    v += 0.25 * (5 + 0.9 * V[2, 3])
                elif new_row < 0 or new_row >= 5 or new_col < 0 or new_col >= 5:
                    v += 0.25 * (-1 + 0.9 * V[row, col])
                else:
                    v += 0.25 * 0.9 * V[new_row, new_col]
            new_V[row, col] = v
    return new_V

In [60]:
def get_poilcy(V: np.ndarray):	
    dir_table = {0: "↑", 1:"↓", 2: "←", 3: "→"}
    direction_list = []
     
    for row in range(5):
        direction_list_row = []
        for col in range(5):
            if row == 0 and col == 1 or row == 0 and col == 3:
                direction_list_row.append("*")
                continue

            action_value = []
            for row_act, col_act in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                new_row = row + row_act
                new_col = col + col_act

                if new_row < 0 or new_row >= 5 or new_col < 0 or new_col >= 5:
                    action_value.append(-np.inf)
                else:
                    action_value.append(V[new_row, new_col])

            best_action = np.argmax(action_value)
            direction_list_row.append(dir_table[best_action])
        direction_list.append(direction_list_row)
    return np.array(direction_list)

In [61]:
V = np.zeros((5, 5))

for i in range(100):
    V = update(V)

print(V)

[[ 3.30899932  8.78929484  4.42762216  5.32237057  1.49218174]
 [ 1.52159105  2.99232084  2.25014293  1.90757468  0.54740569]
 [ 0.05082547  0.73817357  0.67311624  0.35818919 -0.40313816]
 [-0.97358932 -0.43549245 -0.35487929 -0.58560211 -1.1830721 ]
 [-1.85769757 -1.34522828 -1.22926428 -1.42291517 -1.97517607]]


In [62]:
policy = get_poilcy(V)
print(policy)

[['→' '*' '←' '*' '←']
 ['↑' '↑' '↑' '↑' '←']
 ['↑' '↑' '↑' '↑' '↑']
 ['↑' '↑' '↑' '↑' '↑']
 ['↑' '↑' '↑' '↑' '↑']]
