In [2]:
import numpy as np

In [3]:
def update(Q: np.ndarray):
    new_Q = Q.copy()
    for row in range(5):
        for col in range(5):
            for action in range(4):
                new_row = row + [-1, 1, 0, 0][action]
                new_col = col + [0, 0, -1, 1][action]
                if row == 0 and col == 1:
                    new_Q[row, col, action] = 10 + 0.9 * np.max(Q[4, 1, :])
                elif row == 0 and col == 3:
                    new_Q[row, col, action] = 5 + 0.9 * np.max(Q[2, 3, :])
                elif new_row < 0 or new_row >= 5 or new_col < 0 or new_col >= 5:
                    new_Q[row, col, action] = -1 + 0.9 * np.max(Q[row, col, :])
                else:
                    new_Q[row, col, action] = 0.9 * np.max(Q[new_row, new_col, :])
    return new_Q

In [4]:
def get_policy(Q: np.ndarray):
    def TF_to_arrow_(val):
        msg = ""
        directions = ["↑", "↓", "←", "→"]
        for i in range(4):
            if val[i]:
                msg += directions[i]
        if msg == "↑↓←→":
            msg = "* "
        if len(msg) == 1:
            msg += " "
        return msg
    
    TF_to_arrow = np.vectorize(TF_to_arrow_, signature='(n)->()')
    policy = TF_to_arrow(np.array(np.isclose(Q, np.max(Q, axis=2)[:, :, None])))

    return policy

In [5]:
Q = np.zeros((5, 5, 4))

for i in range(100):
    Q = update(Q)

print(np.max(Q, axis=2))

[[21.97690153 24.41877948 21.97690153 19.41877948 17.47690153]
 [19.77921138 21.97690153 19.77921138 17.80129024 16.02116122]
 [17.80129024 19.77921138 17.80129024 16.02116122 14.41877948]
 [16.02116122 17.80129024 16.02116122 14.41877948 12.97690153]
 [14.41877948 16.02116122 14.41877948 12.97690153 11.67921138]]


In [6]:
policy = get_policy(Q)
print(policy)

[['→ ' '* ' '← ' '* ' '← ']
 ['↑→' '↑ ' '↑←' '← ' '← ']
 ['↑→' '↑ ' '↑←' '↑←' '↑←']
 ['↑→' '↑ ' '↑←' '↑←' '↑←']
 ['↑→' '↑ ' '↑←' '↑←' '↑←']]
